FROM openjdk:17

COPY target/*.jar /app/

WORKDIR /app

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "SpringbootMysqlproject-0.0.1-SNAPSHOT.jar"]


# FROM openjdk

# COPY target/*.jar /

# EXPOSE 8080 

# ENTRYPOINT ["java","-jar","/SpringbootMysqlproject-0.0.1-SNAPSHOT.jar"]
